-- Real communities for the finder, replacing the 40 placeholders.
--
-- Entries with needs_verification = false were read from the community's own published rules on 2026-10-08 (the rules
-- text and the page it came from are in rules_summary). Entries with needs_verification = true are real places whose
-- rules could not be read from a first-party page (Reddit blocks automated reading; some Slack rules are only shown
-- after joining). They stay hidden from normal users and are visible to platform operators until someone reads the rules
-- and sets needs_verification = false with a new last_verified_at in a later migration.
--
-- Nothing scrapes or monitors any platform. Rules change: re-check before relying on them.
--
-- Rollback (dev only): delete from public.communities where id::text like 'b0000000-0000-4000-8000-0000000001__'
--   or id::text like 'b0000000-0000-4000-8000-0000000002__' or id::text like 'b0000000-0000-4000-8000-0000000003__';
--   (the four ids ending 001 to 004 were placeholders before; restore them from 20261015000001_finder.sql).

delete from public.communities where name like '[Placeholder]%' and id not in (
  'b0000000-0000-4000-8000-000000000001', 'b0000000-0000-4000-8000-000000000002', 'b0000000-0000-4000-8000-000000000003', 'b0000000-0000-4000-8000-000000000004'
);

insert into public.communities (id, name, platform, url, niches, audience, rules_summary, self_promo_policy, needs_verification, last_verified_at, active) values
  ('b0000000-0000-4000-8000-000000000001', 'Hacker News (Show HN)', 'forum', 'https://news.ycombinator.com/show', array['development','saas','startups','ai'], 'Developers, technical founders and curious people who like to try things out.', 'Show HN is for something you made and can discuss, that people can try out. Not allowed: blog posts, sign-up pages, newsletters, lists, landing pages. Do not ask friends to upvote. Sources: news.ycombinator.com/showhn.html and /newsguidelines.html, read 2026-10-08.', 'Posting your own work is fine part of the time, but the site should not be used primarily for promotion. A case study is a blog post, so it cannot be a Show HN; share one only if it teaches something interesting.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000002', 'DEV Community', 'forum', 'https://dev.to/', array['development','saas','ai'], 'Software developers who write and read posts about building things.', 'Content must be on topic and good quality, with substantial content in the post itself (not just a link to the full post). Affiliate links must be disclosed. Posts designed mainly for promotion or backlinks can be removed. Source: dev.to/terms (content policy) and dev.to/code-of-conduct, read 2026-10-08.', 'Allowed when it is a real, substantial write-up that helps readers. Not allowed: posts designed primarily for promotion or backlinks.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000003', 'Product Hunt forums', 'forum', 'https://www.producthunt.com/p/self-promotion', array['startups','saas','marketing'], 'Makers, founders and early adopters of new tech products.', 'Forums are for questions, feedback and connecting with other makers. Not allowed: using the forums mainly to promote, excessive self-promotion or spam, link dropping without context. Source: help.producthunt.com forum guidelines, read 2026-10-08.', 'There is one topic for it: the Self-Promotion forum, to show off what you are working on. Elsewhere, add meaningful context instead of dropping links.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000004', 'Shopify Community', 'forum', 'https://community.shopify.com/', array['ecommerce','agency','development'], 'Shopify merchants, store builders, partners and developers.', 'Promoting products, services, websites or blogs is not allowed outside the Ask and Offer board. No promotional links to third-party blogs or consultancy sites in replies. Do not post email, phone or WhatsApp details in replies; put them in your profile bio. Disclose any ownership or commercial relationship and be clear about fees. Source: community.shopify.com/guidelines, read 2026-10-08.', 'Only on the Ask and Offer board, with your relationship and fees disclosed. Elsewhere, help people without promoting.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000101', 'OpenAI Developer Community', 'forum', 'https://community.openai.com/', array['ai','development','saas'], 'Developers building with the OpenAI API, ChatGPT and related tools.', 'Do not promote or advertise services unrelated to OpenAI products, developer work or the category. Spamming members with pitches or other self-promotion is not tolerated. Source: community.openai.com/guidelines, read 2026-10-08.', 'Only what is relevant to building with OpenAI products. No unsolicited pitches.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000102', 'Hugging Face Forums', 'forum', 'https://discuss.huggingface.co/', array['ai','development'], 'Machine learning practitioners and people building with open models.', 'Do not post spam or vandalise the forum, and do not cross-post identical content across topics. Do not post other people''s content without permission. The guidelines have no separate self-promotion section. Source: discuss.huggingface.co/guidelines, read 2026-10-08.', 'No dedicated rule found. Treat promotion carefully: contribute first, avoid cross-posting the same post.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000103', 'Webflow Community', 'forum', 'https://community.webflow.com/', array['design','development','agency'], 'Webflow designers, developers and freelancers or agencies building on Webflow.', 'Share relevant insights and avoid self-promotion, ads or unrelated links. Do not share links repeatedly or you may be restricted. Avoid cross-posting the same content. Spam or excessive self-promotion leads to removal, warnings or suspension. Source: community.webflow.com/community-guidelines, read 2026-10-08.', 'Avoid self-promotion. Be useful and share only relevant links.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000104', 'Vercel Community', 'forum', 'https://community.vercel.com/', array['development','saas'], 'Developers and teams deploying on Vercel.', 'The Code of Conduct forbids content that is advertising, self-promotion or solicitations, spamming irrelevant content, and posting the same or similar content multiple times. Source: community.vercel.com/guidelines, read 2026-10-08.', 'Not allowed. Be visible by answering questions well.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000105', 'Bubble Forum', 'forum', 'https://forum.bubble.io/', array['development','saas','agency'], 'Builders, freelancers and agencies using the Bubble no-code platform.', 'Do not send direct messages that could be spam. Do not derail other people''s topics towards your own competing solutions, apps or products. Do not approach members only to move their apps off Bubble. Has a Showcase category (Apps, Templates, Plugins) for what you built on Bubble. Source: forum.bubble.io/guidelines and the Showcase category, read 2026-10-08.', 'Showcase what you built on Bubble in the Showcase category. No spam messages and no pitching competing products inside other people''s topics.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000106', 'Superpath', 'slack', 'https://superpath.co/', array['marketing','agency'], 'In-house, freelance and agency content marketers. Free network plus a paid private community.', 'A Slack community for people who work in content. Its stated purpose: join to learn, share, support and contribute, not to promote. Free members get the newsletter and podcast; the paid Pro community has more private channels. Source: superpath.co, read 2026-10-08.', 'Not for promotion by its own stated purpose. Contribute and share lessons.', false, '2026-10-08', true),
  ('b0000000-0000-4000-8000-000000000201', 'Product Marketing Alliance', 'slack', 'https://www.productmarketingalliance.com/', array['marketing','saas'], 'Product marketers at all levels.', 'Has a Slack community, meetups and events. The site does not publish community rules; read the Slack welcome message.', 'Unknown: read the rules when you join.', true, null, true),
  ('b0000000-0000-4000-8000-000000000202', 'Figma Forum', 'forum', 'https://forum.figma.com/', array['design'], 'Figma users of all levels.', 'Has a Showcase Your Work category and a Forum News and Guidelines section. The guideline text was not read.', 'Unknown: read the Forum News and Guidelines section.', true, null, true),
  ('b0000000-0000-4000-8000-000000000203', 'Zapier Community', 'forum', 'https://community.zapier.com/', array['saas','agency'], 'Zapier users, community experts and staff, with a Hire an Expert link.', 'A forum for asking, learning and sharing about automation. Its code of conduct was not read.', 'Unknown: read the community guidelines.', true, null, true),
  ('b0000000-0000-4000-8000-000000000204', 'WordPress Slack', 'slack', 'https://make.wordpress.org/chat/', array['development','agency'], 'WordPress contributors. Not a support channel.', 'The main real-time chat of the WordPress project; log in with a WordPress.org account. Channel rules on promotion were not read.', 'Unknown: read each channel''s rules. Support questions belong on the WordPress.org forums.', true, null, true),
  ('b0000000-0000-4000-8000-000000000205', 'WooCommerce Community Slack', 'slack', 'https://woocommerce.com/community-slack/', array['ecommerce','development'], 'WooCommerce developers.', 'A Slack workspace of WooCommerce developers. Its rules on promotion were not read.', 'Unknown: read the pinned rules when you join.', true, null, true),
  ('b0000000-0000-4000-8000-000000000206', 'Indie Hackers', 'forum', 'https://www.indiehackers.com/', array['saas','startups'], 'Founders building profitable online businesses.', 'Members report that posting access depends on a pattern of contributing, and that a Show IH flair allows one self-promotion post for feedback. This comes from member posts, not an official rules page, which could not be read.', 'Unknown: contribute first, then check the official guidelines.', true, null, true),
  ('b0000000-0000-4000-8000-000000000301', 'r/SaaS', 'reddit', 'https://www.reddit.com/r/SaaS/', array['saas','startups'], 'Founders and operators building subscription software.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000302', 'r/startups', 'reddit', 'https://www.reddit.com/r/startups/', array['startups','saas'], 'Founders and people starting companies.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000303', 'r/Entrepreneur', 'reddit', 'https://www.reddit.com/r/Entrepreneur/', array['startups','consulting','marketing'], 'Entrepreneurs and small business owners.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000304', 'r/smallbusiness', 'reddit', 'https://www.reddit.com/r/smallbusiness/', array['consulting','marketing','ecommerce'], 'Small business owners and operators.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000305', 'r/marketing', 'reddit', 'https://www.reddit.com/r/marketing/', array['marketing','agency'], 'Marketing professionals.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000306', 'r/digital_marketing', 'reddit', 'https://www.reddit.com/r/digital_marketing/', array['marketing','agency'], 'Digital marketers.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000307', 'r/webdev', 'reddit', 'https://www.reddit.com/r/webdev/', array['development','agency'], 'Web developers.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000308', 'r/web_design', 'reddit', 'https://www.reddit.com/r/web_design/', array['design','agency'], 'Web designers.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000309', 'r/ecommerce', 'reddit', 'https://www.reddit.com/r/ecommerce/', array['ecommerce','marketing'], 'Online store owners and operators.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000310', 'r/shopify', 'reddit', 'https://www.reddit.com/r/shopify/', array['ecommerce','agency'], 'Shopify merchants and developers.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000311', 'r/SideProject', 'reddit', 'https://www.reddit.com/r/SideProject/', array['startups','development'], 'People sharing side projects.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000312', 'r/indiehackers', 'reddit', 'https://www.reddit.com/r/indiehackers/', array['saas','startups'], 'Indie founders.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true),
  ('b0000000-0000-4000-8000-000000000313', 'r/consulting', 'reddit', 'https://www.reddit.com/r/consulting/', array['consulting'], 'Consultants and people in consulting.', 'Reddit could not be read automatically, so this community''s rules are not checked. Read the rules in the sidebar before posting, and check how it treats self-promotion.', 'Unknown: read the subreddit rules.', true, null, true)
on conflict (id) do update
  set name = excluded.name, platform = excluded.platform, url = excluded.url, niches = excluded.niches, audience = excluded.audience,
      rules_summary = excluded.rules_summary, self_promo_policy = excluded.self_promo_policy,
      needs_verification = excluded.needs_verification, last_verified_at = excluded.last_verified_at, active = excluded.active;
